export const placeholders = [
  "Inception",
  "Top Gun: Maverick",
  "Interstellar",
  "The Dark Knight",
  "Blade Runner 2049",
  "La La Land",
  "The Wolf Of Wall Street",
  "The Shawshank Redemption",
  "The Godfather",
  "Rogue One: A Star Wars Story",
  "The Matrix",
  "The Social Network",
  "Infinity War",
  "Dark Knight Rises",
  "Civil War",
];
